name: MyWorkflow file 

on:
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: Ubuntu-20.04

    steps: 
      - name: greeting steps
        run:
          echo "Hello there"

      - name: Checkout my codes
        uses: action/checkout@v4
      - name: print content 
        run: 
          ls 
          
      
