name: MyWorkflow file 

on:
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: Ubuntu-20.04

    steps: 
    - name: greeting steps
      run:
        echo "Hello there"

    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content 
      run: 
        ls 

    # this is where i install python
    - name: Installing python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: check version of python 
      run: 
         python --version 
          
      
